title: Red
description: Kink enthusiast
author:
  name: libido-slave
  email: libido.slave@gmail.com
theme: minima
minima:
  skin: dark
  social_links:
    - title: libido_slave at X (formerly Twitter)
      icon: x-twitter
      url: "https://x.com/libido_slave"